/* Destination names and flags, in one place.
 *
 * The search page, the homepage teaser and the twelve join pages all
 * need to turn an airport code into a city name and a flag. When only
 * the search knew them, two codes with no entry (BSZ, DSE) silently
 * vanished from the results, so this now lives on its own and the daily
 * job shouts if a new code turns up without a name.
 *
 * search.js keeps its own copy so it never depends on load order.
 */
window.CH_PLACES = {
    BCN:["Barcelona","Spain","🇪🇸"],AYT:["Antalya","Türkiye","🇹🇷"],
    IST:["Istanbul","Türkiye","🇹🇷"],MOW:["Moscow","Russia","🇷🇺"],
    LED:["St Petersburg","Russia","🇷🇺"],EDI:["Edinburgh","Scotland","🏴"],
    PAR:["Paris","France","🇫🇷"],AGP:["Málaga","Spain","🇪🇸"],
    ALC:["Alicante","Spain","🇪🇸"],OSS:["Osh","Kyrgyzstan","🇰🇬"],
    FAO:["Faro","Portugal","🇵🇹"],TAS:["Tashkent","Uzbekistan","🇺🇿"],
    BFS:["Belfast","N. Ireland","🇬🇧"],KRK:["Kraków","Poland","🇵🇱"],
    AMS:["Amsterdam","Netherlands","🇳🇱"],PMI:["Palma","Spain","🇪🇸"],
    LIS:["Lisbon","Portugal","🇵🇹"],BAK:["Baku","Azerbaijan","🇦🇿"],
    ACE:["Lanzarote","Spain","🇪🇸"],MAD:["Madrid","Spain","🇪🇸"],
    BKK:["Bangkok","Thailand","🇹🇭"],LON:["London","England","🏴"],
    YTO:["Toronto","Canada","🇨🇦"],PRG:["Prague","Czechia","🇨🇿"],
    ALA:["Almaty","Kazakhstan","🇰🇿"],SKD:["Samarkand","Uzbekistan","🇺🇿"],
    DUB:["Dublin","Ireland","🇮🇪"],WAW:["Warsaw","Poland","🇵🇱"],
    BER:["Berlin","Germany","🇩🇪"],LPA:["Gran Canaria","Spain","🇪🇸"],
    BEG:["Belgrade","Serbia","🇷🇸"],NYC:["New York","USA","🇺🇸"],
    DUS:["Düsseldorf","Germany","🇩🇪"],RMO:["Chișinău","Moldova","🇲🇩"],
    GRO:["Girona","Spain","🇪🇸"],HAM:["Hamburg","Germany","🇩🇪"],
    TCI:["Tenerife","Spain","🇪🇸"],CIT:["Shymkent","Kazakhstan","🇰🇿"],
    DLM:["Dalaman","Türkiye","🇹🇷"],CPH:["Copenhagen","Denmark","🇩🇰"],
    HEL:["Helsinki","Finland","🇫🇮"],DXB:["Dubai","UAE","🇦🇪"],
    CGN:["Cologne","Germany","🇩🇪"],BIO:["Bilbao","Spain","🇪🇸"],
    DYU:["Dushanbe","Tajikistan","🇹🇯"],TBS:["Tbilisi","Georgia","🇬🇪"],
    BUD:["Budapest","Hungary","🇭🇺"],NQZ:["Astana","Kazakhstan","🇰🇿"],
    OSL:["Oslo","Norway","🇳🇴"],OPO:["Porto","Portugal","🇵🇹"],
    IZM:["Izmir","Türkiye","🇹🇷"],GLA:["Glasgow","Scotland","🏴"],
    ROM:["Rome","Italy","🇮🇹"],VIE:["Vienna","Austria","🇦🇹"],
    LOS:["Lagos","Nigeria","🇳🇬"],BRS:["Bristol","England","🏴"],
    LHE:["Lahore","Pakistan","🇵🇰"],JNB:["Johannesburg","South Africa","🇿🇦"],
    HKG:["Hong Kong","Hong Kong","🇭🇰"],VNO:["Vilnius","Lithuania","🇱🇹"],
    BRI:["Bari","Italy","🇮🇹"],KZN:["Kazan","Russia","🇷🇺"],
    AGA:["Agadir","Morocco","🇲🇦"],CWL:["Cardiff","Wales","🏴"],
    MLA:["Malta","Malta","🇲🇹"],MAN:["Manchester","England","🏴"],
    REU:["Reus","Spain","🇪🇸"],JMK:["Mykonos","Greece","🇬🇷"],
    HKT:["Phuket","Thailand","🇹🇭"],SYD:["Sydney","Australia","🇦🇺"],
    BHX:["Birmingham","England","🏴"],AER:["Sochi","Russia","🇷🇺"],
    KRR:["Krasnodar","Russia","🇷🇺"],ILY:["Islay","Scotland","🏴"],
    KOI:["Kirkwall","Scotland","🏴"],FRA:["Frankfurt","Germany","🇩🇪"],
    GBE:["Gaborone","Botswana","🇧🇼"],MCX:["Makhachkala","Russia","🇷🇺"],
    LPL:["Liverpool","England","🏴"],RAK:["Marrakesh","Morocco","🇲🇦"],
    OLB:["Olbia","Italy","🇮🇹"],FUE:["Fuerteventura","Spain","🇪🇸"],
    PFO:["Paphos","Cyprus","🇨🇾"],ORK:["Cork","Ireland","🇮🇪"],
    NCL:["Newcastle","England","🏴"],KUN:["Kaunas","Lithuania","🇱🇹"],
    DBV:["Dubrovnik","Croatia","🇭🇷"],CLT:["Charlotte","USA","🇺🇸"],
    MSQ:["Minsk","Belarus","🇧🇾"],CAG:["Cagliari","Italy","🇮🇹"],
    KTT:["Kittilä","Finland","🇫🇮"],PRN:["Pristina","Kosovo","🇽🇰"],
    FAE:["Faroe Islands","Faroes","🇫🇴"],ORL:["Orlando","USA","🇺🇸"],
    MIR:["Monastir","Tunisia","🇹🇳"],HAK:["Haikou","China","🇨🇳"],
    EBL:["Erbil","Iraq","🇮🇶"],CAI:["Cairo","Egypt","🇪🇬"],
    FNA:["Freetown","Sierra Leone","🇸🇱"],JED:["Jeddah","Saudi Arabia","🇸🇦"],
    GDN:["Gdańsk","Poland","🇵🇱"],ACC:["Accra","Ghana","🇬🇭"],
    ATQ:["Amritsar","India","🇮🇳"],BUH:["Bucharest","Romania","🇷🇴"],
    BOD:["Bordeaux","France","🇫🇷"],CLJ:["Cluj-Napoca","Romania","🇷🇴"],
    BOS:["Boston","USA","🇺🇸"],BOJ:["Burgas","Bulgaria","🇧🇬"],
    GIB:["Gibraltar","Gibraltar","🇬🇮"],IBZ:["Ibiza","Spain","🇪🇸"],
    CHQ:["Chania","Greece","🇬🇷"],CFU:["Corfu","Greece","🇬🇷"],
    KTM:["Kathmandu","Nepal","🇳🇵"],SJO:["San José","Costa Rica","🇨🇷"],
    NCE:["Nice","France","🇫🇷"],KUT:["Kutaisi","Georgia","🇬🇪"],
    BUS:["Batumi","Georgia","🇬🇪"],ZTH:["Zakynthos","Greece","🇬🇷"],
    SSH:["Sharm el-Sheikh","Egypt","🇪🇬"],MIL:["Milan","Italy","🇮🇹"],
    ABV:["Abuja","Nigeria","🇳🇬"],ISB:["Islamabad","Pakistan","🇵🇰"],
    BRU:["Brussels","Belgium","🇧🇪"],BJV:["Bodrum","Türkiye","🇹🇷"],
    BSZ:["Bartica","Guyana","🇬🇾"],DSE:["Dessie","Ethiopia","🇪🇹"],
    ABZ:["Aberdeen","United Kingdom","🇬🇧"],
    AJA:["Ajaccio","France","🇫🇷"],
    AUA:["Oranjestad","Aruba","🇦🇼"],
    BLR:["Bengaluru","India","🇮🇳"],
    BNX:["Banja Luka","Bosnia and Herzegovina","🇧🇦"],
    BOH:["Bournemouth","United Kingdom","🇬🇧"],
    BUF:["Buffalo","USA","🇺🇸"],
    CFN:["Carrickfinn","Ireland","🇮🇪"],
    CMF:["Chambery","France","🇫🇷"],
    COK:["Kochi","India","🇮🇳"],
    CUN:["Cancun","Mexico","🇲🇽"],
    DAC:["Dhaka","Bangladesh","🇧🇩"],
    EAP:["Basel","Switzerland","🇨🇭"],
    EVN:["Yerevan","Armenia","🇦🇲"],
    EXT:["Exeter","United Kingdom","🇬🇧"],
    GRV:["Groznyy","Russia","🇷🇺"],
    GVA:["Geneva","Switzerland","🇨🇭"],
    HER:["Heraklion","Greece","🇬🇷"],
    INV:["Inverness","United Kingdom","🇬🇧"],
    JLR:["Jabalpur","India","🇮🇳"],
    KCH:["Kuching","Malaysia","🇲🇾"],
    KUU:["Bhuntar Kullu","India","🇮🇳"],
    LCA:["Larnaca","Cyprus","🇨🇾"],
    LUX:["Luxembourg","Luxembourg","🇱🇺"],
    MAH:["Menorca","Spain","🇪🇸"],
    MUX:["Multan","Pakistan","🇵🇰"],
    NBC:["Naberezhnye Chelny","Russia","🇷🇺"],
    NQY:["Newquay","United Kingdom","🇬🇧"],
    NWI:["Norwich","United Kingdom","🇬🇧"],
    OST:["Bruges","Belgium","🇧🇪"],
    OVB:["Novosibirsk","Russia","🇷🇺"],
    RHO:["Rhodes","Greece","🇬🇷"],
    RIX:["Riga","Latvia","🇱🇻"],
    SCV:["Suceava","Romania","🇷🇴"],
    SNN:["Shannon","Ireland","🇮🇪"],
    SOU:["Southampton","United Kingdom","🇬🇧"],
    SPU:["Split","Croatia","🇭🇷"],
    SVQ:["Sevilla","Spain","🇪🇸"],
    TLL:["Tallinn","Estonia","🇪🇪"],
    TOS:["Tromso","Norway","🇳🇴"],
    UGC:["Urgench","Uzbekistan","🇺🇿"],
    VCE:["Venice","Italy","🇮🇹"],
    VLC:["Valencia","Spain","🇪🇸"],
    WAS:["Washington","USA","🇺🇸"],
    WRO:["Wroclaw","Poland","🇵🇱"],
    YYC:["Calgary","Canada","🇨🇦"],
    ZRH:["Zurich","Switzerland","🇨🇭"],
    AAE:["Annaba","Algeria","🇩🇿"],
    AAL:["Aalborg","Denmark","🇩🇰"],
    AAR:["Aarhus","Denmark","🇩🇰"],
    ABA:["Abakan","Russia","🇷🇺"],
    ABS:["Abu Simbel","Egypt","🇪🇬"],
    ACI:["Alderney","United Kingdom","🇬🇧"],
    ADD:["Addis Ababa","Ethiopia","🇪🇹"],
    ADL:["Adelaide","Australia","🇦🇺"],
    AES:["Aalesund","Norway","🇳🇴"],
    AEY:["Akureyri","Iceland","🇮🇸"],
    AHO:["Alghero","Italy","🇮🇹"],
    AKL:["Auckland","New Zealand","🇳🇿"],
    AKX:["Aktobe","Kazakhstan","🇰🇿"],
    ALG:["Algiers","Algeria","🇩🇿"],
    ALY:["Alexandria","Egypt","🇪🇬"],
    AMD:["Ahmedabad","India","🇮🇳"],
    ANC:["Anchorage","USA","🇺🇸"],
    ANK:["Ankara","Turkiye","🇹🇷"],
    ANR:["Antwerp","Belgium","🇧🇪"],
    ANU:["Saint John's","Antigua and Barbuda","🇦🇬"],
    AOI:["Ancona","Italy","🇮🇹"],
    ARH:["Arkhangelsk","Russia","🇷🇺"],
    ASB:["Ashgabat","Turkmenistan","🇹🇲"],
    ASF:["Astrakhan","Russia","🇷🇺"],
    ASU:["Asuncion","Paraguay","🇵🇾"],
    ATH:["Athens","Greece","🇬🇷"],
    ATL:["Atlanta","USA","🇺🇸"],
    AUH:["Abu Dhabi","UAE","🇦🇪"],
    AUS:["Austin","USA","🇺🇸"],
    AXA:["Anguilla","Anguilla","🇦🇮"],
    AXM:["Armenia","Colombia","🇨🇴"],
    AZN:["Andijan","Uzbekistan","🇺🇿"],
    BAH:["Manama","Bahrain","🇧🇭"],
    BAX:["Barnaul","Russia","🇷🇺"],
    BCM:["Bacau","Romania","🇷🇴"],
    BDA:["Bermuda","Bermuda","🇧🇲"],
    BDQ:["Vadodara","India","🇮🇳"],
    BDS:["Brindisi","Italy","🇮🇹"],
    BEN:["Benghazi","Libya","🇱🇾"],
    BES:["Brest","France","🇫🇷"],
    BGI:["Bridgetown","Barbados","🇧🇧"],
    BGO:["Bergen","Norway","🇳🇴"],
    BGW:["Baghdad","Iraq","🇮🇶"],
    BHJ:["Bhuj","India","🇮🇳"],
    BHK:["Bukhara","Uzbekistan","🇺🇿"],
    BHM:["Birmingham","USA","🇺🇸"],
    BHZ:["Belo Horizonte","Brazil","🇧🇷"],
    BIA:["Bastia","France","🇫🇷"],
    BIL:["Billings","USA","🇺🇸"],
    BIQ:["Biarritz","France","🇫🇷"],
    BIS:["Bismarck","USA","🇺🇸"],
    BJL:["Banjul","Gambia","🇬🇲"],
    BJS:["Beijing","China","🇨🇳"],
    BKO:["Bamako","Mali","🇲🇱"],
    BLL:["Billund","Denmark","🇩🇰"],
    BLQ:["Bologna","Italy","🇮🇹"],
    BLZ:["Blantyre","Malawi","🇲🇼"],
    BNA:["Nashville","USA","🇺🇸"],
    BNE:["Brisbane","Australia","🇦🇺"],
    BOB:["Bora Bora","French Polynesia","🇵🇫"],
    BOG:["Bogota","Colombia","🇨🇴"],
    BOM:["Mumbai","India","🇮🇳"],
    BOO:["Bodo","Norway","🇳🇴"],
    BPN:["Balikpapan","Indonesia","🇮🇩"],
    BQS:["Blagoveschensk","Russia","🇷🇺"],
    BQT:["Brest","Belarus","🇧🇾"],
    BRC:["San Carlos de Bariloche","Argentina","🇦🇷"],
    BRE:["Bremen","Germany","🇩🇪"],
    BRN:["Bern","Switzerland","🇨🇭"],
    BRQ:["Brno","Czechia","🇨🇿"],
    BRR:["Barra","United Kingdom","🇬🇧"],
    BSB:["Brasilia","Brazil","🇧🇷"],
    BSR:["Basra","Iraq","🇮🇶"],
    BTK:["Bratsk","Russia","🇷🇺"],
    BTS:["Bratislava","Slovakia","🇸🇰"],
    BUE:["Buenos Aires","Argentina","🇦🇷"],
    BUQ:["Bulawayo","Zimbabwe","🇿🇼"],
    BVC:["Boa Vista","Cape Verde","🇨🇻"],
    BVE:["Brive-La-Gaillarde","France","🇫🇷"],
    BWI:["Baltimore","USA","🇺🇸"],
    BZE:["Belize City","Belize","🇧🇿"],
    BZG:["Bydgoszcz","Poland","🇵🇱"],
    BZO:["Bolzano","Italy","🇮🇹"],
    BZR:["Beziers","France","🇫🇷"],
    BZV:["Brazzaville","Republic of the Congo","🇨🇬"],
    CAK:["Akron","USA","🇺🇸"],
    CAL:["Campbeltown","United Kingdom","🇬🇧"],
    CAN:["Guangzhou","China","🇨🇳"],
    CBR:["Canberra","Australia","🇦🇺"],
    CCF:["Carcassonne","France","🇫🇷"],
    CCS:["Caracas","Venezuela","🇻🇪"],
    CCU:["Kolkata","India","🇮🇳"],
    CEB:["Cebu City","Philippines","🇵🇭"],
    CEE:["Cherepovets","Russia","🇷🇺"],
    CEK:["Chelyabinsk","Russia","🇷🇺"],
    CFE:["Clermont-Ferrand","France","🇫🇷"],
    CFR:["Caen","France","🇫🇷"],
    CHC:["Christchurch","New Zealand","🇳🇿"],
    CHI:["Chicago","USA","🇺🇸"],
    CJU:["Jeju","South Korea","🇰🇷"],
    CKB:["Clarksburg","USA","🇺🇸"],
    CKG:["Chongqing","China","🇨🇳"],
    CKY:["Conakry","Guinea","🇬🇳"],
    CKZ:["Canakkale","Turkiye","🇹🇷"],
    CLE:["Cleveland","USA","🇺🇸"],
    CLO:["Cali","Colombia","🇨🇴"],
    CMB:["Colombo","Sri Lanka","🇱🇰"],
    CMH:["Columbus","USA","🇺🇸"],
    CMN:["Casablanca","Morocco","🇲🇦"],
    CND:["Constanta","Romania","🇷🇴"],
    CNN:["Kannur","India","🇮🇳"],
    CNS:["Cairns","Australia","🇦🇺"],
    CNX:["Chiang Mai","Thailand","🇹🇭"],
    COO:["Cotonou","Benin","🇧🇯"],
    COS:["Colorado Springs","USA","🇺🇸"],
    COV:["Mersin","Turkiye","🇹🇷"],
    CPT:["Cape Town","South Africa","🇿🇦"],
    CRA:["Craiova","Romania","🇷🇴"],
    CSX:["Changsha","China","🇨🇳"],
    CSY:["Cheboksary","Russia","🇷🇺"],
    CTA:["Catania","Italy","🇮🇹"],
    CTU:["Chengdu","China","🇨🇳"],
    CUR:["Curacao","CuraÃ§ao","🇨🇼"],
    CUZ:["Cusco","Peru","🇵🇪"],
    CVG:["Cincinnati","USA","🇺🇸"],
    DAD:["Da Nang","Vietnam","🇻🇳"],
    DAR:["Dar Es Salaam","Tanzania","🇹🇿"],
    DEE:["Yuzhno-Kurilsk","Russia","🇷🇺"],
    DEL:["New Delhi","India","🇮🇳"],
    DEN:["Denver","USA","🇺🇸"],
    DFW:["Dallas","USA","🇺🇸"],
    DIL:["Dili","East Timor","🇹🇱"],
    DJE:["Djerba","Tunisia","🇹🇳"],
    DLC:["Dalian","China","🇨🇳"],
    DLI:["Dalat","Vietnam","🇻🇳"],
    DND:["Dundee","United Kingdom","🇬🇧"],
    DOH:["Doha","Qatar","🇶🇦"],
    DOL:["Deauville","France","🇫🇷"],
    DOM:["Dominica","Dominica","🇩🇲"],
    DPS:["Denpasar (Bali)","Indonesia","🇮🇩"],
    DRS:["Dresden","Germany","🇩🇪"],
    DRW:["Darwin","Australia","🇦🇺"],
    DTM:["Dortmund","Germany","🇩🇪"],
    DTT:["Detroit","USA","🇺🇸"],
    DUR:["Durban","South Africa","🇿🇦"],
    DYG:["Dayong","China","🇨🇳"],
    EAS:["San Sebastian","Spain","🇪🇸"],
    EBB:["Entebbe","Uganda","🇺🇬"],
    EBJ:["Esbjerg","Denmark","🇩🇰"],
    ECN:["Ercan","Northern Cyprus","🇳🇾"],
    EFL:["Kefallinia","Greece","🇬🇷"],
    EGC:["Bergerac","France","🇫🇷"],
    EGS:["Egilsstadir","Iceland","🇮🇸"],
    EIN:["Eindhoven","Netherlands","🇳🇱"],
    EIS:["Beef Island","British Virgin Islands","🇻🇬"],
    ELH:["North Eleuthera","Bahamas","🇧🇸"],
    ERF:["Erfurt","Germany","🇩🇪"],
    ESU:["Essaouira","Morocco","🇲🇦"],
    EUX:["St Eustatius","Netherlands","🇳🇱"],
    EVE:["Harstad-Narvik","Norway","🇳🇴"],
    FAR:["Fargo","USA","🇺🇸"],
    FBM:["Lubumbashi","Democratic Republic of the Congo","🇨🇩"],
    FDF:["Fort-de-France","Martinique","🇲🇶"],
    FEG:["Fergana","Uzbekistan","🇺🇿"],
    FEZ:["Fez","Morocco","🇲🇦"],
    FIH:["Kinshasa","Democratic Republic of the Congo","🇨🇩"],
    FKB:["Karlsruhe","Germany","🇩🇪"],
    FLL:["Fort Lauderdale","USA","🇺🇸"],
    FLN:["Florianopolis","Brazil","🇧🇷"],
    FLR:["Florence","Italy","🇮🇹"],
    FLW:["Flores Island (Azores)","Portugal","🇵🇹"],
    FMM:["Memmingen","Germany","🇩🇪"],
    FNC:["Funchal","Portugal","🇵🇹"],
    FNI:["Nimes","France","🇫🇷"],
    FOG:["Foggia","Italy","🇮🇹"],
    FOR:["Fortaleza","Brazil","🇧🇷"],
    FUK:["Fukuoka","Japan","🇯🇵"],
    GAN:["Gan Island","Maldives","🇲🇻"],
    GCI:["Guernsey","Guernsey","🇬🇬"],
    GCM:["Georgetown","Cayman Islands","🇰🇾"],
    GDT:["Grand Turk","Turks and Caicos Islands","🇹🇨"],
    GDZ:["Gelendzik","Russia","🇷🇺"],
    GHV:["Brasov","Romania","🇷🇴"],
    GME:["Gomel","Belarus","🇧🇾"],
    GMZ:["San Sebastian de la Gomera","Spain","🇪🇸"],
    GND:["St. George's","Grenada","🇬🇩"],
    GNJ:["Ganja","Azerbaijan","🇦🇿"],
    GOA:["Genoa","Italy","🇮🇹"],
    GOH:["Nuuk","Greenland","🇬🇱"],
    GOI:["Goa","India","🇮🇳"],
    GOJ:["Nizhniy Novgorod","Russia","🇷🇺"],
    GOT:["Gothenburg","Sweden","🇸🇪"],
    GRX:["Granada","Spain","🇪🇸"],
    GRZ:["Graz","Austria","🇦🇹"],
    GUA:["Guatemala City","Guatemala","🇬🇹"],
    GUW:["Atyrau","Kazakhstan","🇰🇿"],
    GYE:["Guayaquil","Ecuador","🇪🇨"],
    GYN:["Goiania","Brazil","🇧🇷"],
    GZP:["Alanya","Turkiye","🇹🇷"],
    GZT:["Gaziantep","Turkiye","🇹🇷"],
    HAJ:["Hannover","Germany","🇩🇪"],
    HAN:["Hanoi","Vietnam","🇻🇳"],
    HAV:["Havana","Cuba","🇨🇺"],
    HBA:["Hobart","Australia","🇦🇺"],
    HDO:["Ghaziabad","India","🇮🇳"],
    HGA:["Hargeisa","Somalia","🇸🇴"],
    HGH:["Hangzhou","China","🇨🇳"],
    HIJ:["Hiroshima","Japan","🇯🇵"],
    HLN:["Helena","USA","🇺🇸"],
    HNL:["Honolulu","USA","🇺🇸"],
    HOU:["Houston","USA","🇺🇸"],
    HOV:["Orsta-Volda","Norway","🇳🇴"],
    HRB:["Harbin","China","🇨🇳"],
    HRE:["Harare","Zimbabwe","🇿🇼"],
    HRG:["Hurghada","Egypt","🇪🇬"],
    HSA:["Turkistan","Kazakhstan","🇰🇿"],
    HTA:["Chita","Russia","🇷🇺"],
    HTY:["Antakya","Turkiye","🇹🇷"],
    HUY:["Humberside","United Kingdom","🇬🇧"],
    HYD:["Hyderabad","India","🇮🇳"],
    IAR:["Yaroslavl","Russia","🇷🇺"],
    IAS:["Iasi","Romania","🇷🇴"],
    IFJ:["Isafjordur","Iceland","🇮🇸"],
    IGT:["Magas","Russia","🇷🇺"],
    IGU:["Foz do IguaÃ§u","Brazil","🇧🇷"],
    IJK:["Izhevsk","Russia","🇷🇺"],
    IKT:["Irkutsk","Russia","🇷🇺"],
    INI:["Nis","Serbia","🇷🇸"],
    INN:["Innsbruck","Austria","🇦🇹"],
    IOM:["Isle Of Man","Isle of Man","🇮🇲"],
    ISU:["Sulaimaniyah","Iraq","🇮🇶"],
    IVL:["Ivalo","Finland","🇫🇮"],
    IWA:["Ivanovo","Russia","🇷🇺"],
    JAI:["Jaipur","India","🇮🇳"],
    JAX:["Jacksonville","USA","🇺🇸"],
    JDH:["Jodhpur","India","🇮🇳"],
    JER:["Jersey","Jersey","🇯🇪"],
    JHB:["Johor Bahru","Malaysia","🇲🇾"],
    JIK:["Ikaria Island","Greece","🇬🇷"],
    JKT:["Jakarta","Indonesia","🇮🇩"],
    JNX:["Naxos","Greece","🇬🇷"],
    JOG:["Yogyakarta","Indonesia","🇮🇩"],
    JRO:["Kilimanjaro","Tanzania","🇹🇿"],
    JSH:["Sitia","Greece","🇬🇷"],
    JSI:["Skiathos","Greece","🇬🇷"],
    JTR:["Thira","Greece","🇬🇷"],
    JTY:["Astypalaia Island","Greece","🇬🇷"],
    KAJ:["Kajaani","Finland","🇫🇮"],
    KAO:["Kuusamo","Finland","🇫🇮"],
    KBL:["Kabul","Afghanistan","🇦🇫"],
    KBV:["Krabi","Thailand","🇹🇭"],
    KEJ:["Kemerovo","Russia","🇷🇺"],
    KGD:["Kaliningrad","Russia","🇷🇺"],
    KGF:["Karagandy","Kazakhstan","🇰🇿"],
    KGL:["Kigali","Rwanda","🇷🇼"],
    KGS:["Kos","Greece","🇬🇷"],
    KHI:["Karachi","Pakistan","🇵🇰"],
    KHV:["Khabarovsk","Russia","🇷🇺"],
    KIN:["Kingston","Jamaica","🇯🇲"],
    KIR:["Kerry County","Ireland","🇮🇪"],
    KJA:["Krasnoyarsk","Russia","🇷🇺"],
    KKN:["Kirkenes","Norway","🇳🇴"],
    KLU:["Klagenfurt","Austria","🇦🇹"],
    KLX:["Kalamata","Greece","🇬🇷"],
    KMS:["Kumasi","Ghana","🇬🇭"],
    KOS:["Sihanoukville","Cambodia","🇰🇭"],
    KOW:["Ganzhou","China","🇨🇳"],
    KQT:["Kurgon-Tyube (Bokhtar)","Tajikistan","🇹🇯"],
    KRN:["Kiruna","Sweden","🇸🇪"],
    KRO:["Kurgan","Russia","🇷🇺"],
    KRS:["Kristiansand","Norway","🇳🇴"],
    KSC:["Kosice","Slovakia","🇸🇰"],
    KSN:["Kostanay","Kazakhstan","🇰🇿"],
    KSQ:["Qarshi","Uzbekistan","🇺🇿"],
    KTW:["Katowice","Poland","🇵🇱"],
    KUF:["Samara","Russia","🇷🇺"],
    KUL:["Kuala Lumpur","Malaysia","🇲🇾"],
    KUO:["Kuopio","Finland","🇫🇮"],
    KVA:["Kavala","Greece","🇬🇷"],
    KVO:["Kraljevo","Serbia","🇷🇸"],
    KVX:["Kirov","Russia","🇷🇺"],
    KWI:["Kuwait City","Kuwait","🇰🇼"],
    KYA:["Konya","Turkiye","🇹🇷"],
    LAD:["Luanda","Angola","🇦🇴"],
    LAS:["Las Vegas","USA","🇺🇸"],
    LAX:["Los Angeles","USA","🇺🇸"],
    LBA:["Leeds","United Kingdom","🇬🇧"],
    LBD:["Khujand","Tajikistan","🇹🇯"],
    LCG:["La Coruna","Spain","🇪🇸"],
    LCJ:["Lodz","Poland","🇵🇱"],
    LDB:["Londrina","Brazil","🇧🇷"],
    LDE:["Lourdes","France","🇫🇷"],
    LDY:["Derry","United Kingdom","🇬🇧"],
    LEI:["Almeria","Spain","🇪🇸"],
    LEJ:["Leipzig/Halle","Germany","🇩🇪"],
    LGK:["Langkawi","Malaysia","🇲🇾"],
    LIG:["Limoges","France","🇫🇷"],
    LIL:["Lille","France","🇫🇷"],
    LIM:["Lima","Peru","🇵🇪"],
    LJU:["Ljubljana","Slovenia","🇸🇮"],
    LKO:["Lucknow","India","🇮🇳"],
    LLA:["Lulea","Sweden","🇸🇪"],
    LMP:["Lampedusa","Italy","🇮🇹"],
    LOP:["Praya","Indonesia","🇮🇩"],
    LPQ:["Luang Prabang","Laos","🇱🇦"],
    LRH:["La Rochelle","France","🇫🇷"],
    LRT:["Lorient","France","🇫🇷"],
    LUN:["Lusaka","Zambia","🇿🇲"],
    LUZ:["Swidnik","Poland","🇵🇱"],
    LWN:["Gyumri","Armenia","🇦🇲"],
    LXR:["Luxor","Egypt","🇪🇬"],
    LYB:["Little Cayman","Cayman Islands","🇰🇾"],
    LYS:["Lyon","France","🇫🇷"],
    LZO:["Luzhou","China","🇨🇳"],
    MAA:["Chennai","India","🇮🇳"],
    MAB:["Maraba","Brazil","🇧🇷"],
    MBA:["Mombasa","Kenya","🇰🇪"],
    MBJ:["Montego Bay","Jamaica","🇯🇲"],
    MCT:["Muscat","Oman","🇴🇲"],
    MDE:["Medellin","Colombia","🇨🇴"],
    MED:["Medina","Saudi Arabia","🇸🇦"],
    MEL:["Melbourne","Australia","🇦🇺"],
    MEX:["Mexico City","Mexico","🇲🇽"],
    MFM:["Macau","Macau","🇲🇴"],
    MGF:["Maringa","Brazil","🇧🇷"],
    MGQ:["Mogadishu","Somalia","🇸🇴"],
    MIA:["Miami","USA","🇺🇸"],
    MKC:["Kansas City","USA","🇺🇸"],
    MLE:["Male","Maldives","🇲🇻"],
    MLW:["Monrovia","Liberia","🇱🇷"],
    MLX:["Malatya","Turkiye","🇹🇷"],
    MMA:["Malmo","Sweden","🇸🇪"],
    MME:["Teesside","United Kingdom","🇬🇧"],
    MMK:["Murmansk","Russia","🇷🇺"],
    MNL:["Manila","Philippines","🇵🇭"],
    MPH:["Caticlan","Philippines","🇵🇭"],
    MPL:["Montpellier","France","🇫🇷"],
    MPM:["Maputo","Mozambique","🇲🇿"],
    MPN:["Mount Pleasant","Falkland Islands","🇫🇰"],
    MQF:["Magnitogorsk","Russia","🇷🇺"],
    MQN:["Mo I Rana","Norway","🇳🇴"],
    MRS:["Marseille","France","🇫🇷"],
    MRU:["Mauritius","Mauritius","🇲🇺"],
    MRV:["Mineralnye Vody","Russia","🇷🇺"],
    MSP:["Minneapolis","USA","🇺🇸"],
    MST:["Maastricht","Netherlands","🇳🇱"],
    MSY:["New Orleans","USA","🇺🇸"],
    MUC:["Munich","Germany","🇩🇪"],
    MVD:["Montevideo","Uruguay","🇺🇾"],
    MZR:["Mazar-i-sharif","Afghanistan","🇦🇫"],
    NAJ:["Nakhichevan","Azerbaijan","🇦🇿"],
    NAL:["Nalchik","Russia","🇷🇺"],
    NAN:["Nadi","Fiji","🇫🇯"],
    NAP:["Naples","Italy","🇮🇹"],
    NAS:["Nassau","Bahamas","🇧🇸"],
    NAT:["Natal","Brazil","🇧🇷"],
    NAV:["Nevsehir","Turkiye","🇹🇷"],
    NBE:["Enfidha","Tunisia","🇹🇳"],
    NBO:["Nairobi","Kenya","🇰🇪"],
    NCU:["Nukus","Uzbekistan","🇺🇿"],
    NDJ:["N'Djamena","Chad","🇹🇩"],
    NER:["Neryungri","Russia","🇷🇺"],
    NGO:["Nagoya","Japan","🇯🇵"],
    NHA:["Nha Trang","Vietnam","🇻🇳"],
    NJC:["Nizhnevartovsk","Russia","🇷🇺"],
    NKC:["Nouakchott","Mauritania","🇲🇷"],
    NKG:["Nanjing","China","🇨🇳"],
    NLI:["Nikolayevsk-na-Amure","Russia","🇷🇺"],
    NMA:["Namangan","Uzbekistan","🇺🇿"],
    NOC:["Knock","Ireland","🇮🇪"],
    NOZ:["Novokuznetsk","Russia","🇷🇺"],
    NQT:["Nottingham","United Kingdom","🇬🇧"],
    NSK:["Norilsk","Russia","🇷🇺"],
    NTE:["Nantes","France","🇫🇷"],
    NTL:["Newcastle","Australia","🇦🇺"],
    NUE:["Nuremberg","Germany","🇩🇪"],
    NUX:["Novy Urengoy","Russia","🇷🇺"],
    NVI:["Navoi","Uzbekistan","🇺🇿"],
    NYM:["Nadym","Russia","🇷🇺"],
    NZH:["Manzhouli","China","🇨🇳"],
    OAK:["Oakland","USA","🇺🇸"],
    ODB:["Cordoba","Spain","🇪🇸"],
    OGZ:["Vladikavkaz","Russia","🇷🇺"],
    OHD:["Ohrid","Macedonia","🇲🇰"],
    OKA:["Okinawa","Japan","🇯🇵"],
    OMO:["Mostar","Bosnia and Herzegovina","🇧🇦"],
    OMS:["Omsk","Russia","🇷🇺"],
    ONT:["Ontario","USA","🇺🇸"],
    OOL:["Gold Coast","Australia","🇦🇺"],
    ORN:["Oran","Algeria","🇩🇿"],
    OSA:["Osaka","Japan","🇯🇵"],
    OSD:["Ostersund","Sweden","🇸🇪"],
    OUD:["Oujda","Morocco","🇲🇦"],
    OVD:["Asturias","Spain","🇪🇸"],
    PAT:["Patna","India","🇮🇳"],
    PBH:["Paro","Bhutan","🇧🇹"],
    PBM:["Paramaribo","Suriname","🇸🇷"],
    PDG:["Padang","Indonesia","🇮🇩"],
    PDL:["Ponta Delgada","Portugal","🇵🇹"],
    PDV:["Plovdiv","Bulgaria","🇧🇬"],
    PDX:["Portland","USA","🇺🇸"],
    PEE:["Perm","Russia","🇷🇺"],
    PEG:["Perugia","Italy","🇮🇹"],
    PEN:["Penang","Malaysia","🇲🇾"],
    PER:["Perth","Australia","🇦🇺"],
    PES:["Petrozavodsk","Russia","🇷🇺"],
    PEW:["Peshawar","Pakistan","🇵🇰"],
    PEZ:["Penza","Russia","🇷🇺"],
    PGF:["Perpignan","France","🇫🇷"],
    PHC:["Port Harcourt","Nigeria","🇳🇬"],
    PHL:["Philadelphia","USA","🇺🇸"],
    PHX:["Phoenix","USA","🇺🇸"],
    PIA:["Peoria","USA","🇺🇸"],
    PIS:["Poitiers","France","🇫🇷"],
    PIT:["Pittsburgh","USA","🇺🇸"],
    PKC:["Petropavlovsk-Kamchatsky","Russia","🇷🇺"],
    PLQ:["Palanga","Lithuania","🇱🇹"],
    PLX:["Semey","Kazakhstan","🇰🇿"],
    PMO:["Palermo","Italy","🇮🇹"],
    PNS:["Pensacola","USA","🇺🇸"],
    PNT:["Puerto Natales","Chile","🇨🇱"],
    POS:["Port Of Spain","Trinidad and Tobago","🇹🇹"],
    POZ:["Poznan","Poland","🇵🇱"],
    PPK:["Petropavl","Kazakhstan","🇰🇿"],
    PPW:["Papa Westray","United Kingdom","🇬🇧"],
    PQC:["Phu Quoc","Vietnam","🇻🇳"],
    PRI:["Praslin Island","Seychelles","🇸🇨"],
    PSA:["Pisa","Italy","🇮🇹"],
    PSR:["Pescara","Italy","🇮🇹"],
    PTP:["Pointe-a-pitre","Guadeloupe","🇬🇵"],
    PTY:["Panama City","Panama","🇵🇦"],
    PUF:["Pau","France","🇫🇷"],
    PUJ:["Punta Cana","Dominican Republic","🇩🇴"],
    PUS:["Busan","South Korea","🇰🇷"],
    PUY:["Pula","Croatia","🇭🇷"],
    PVK:["Preveza","Greece","🇬🇷"],
    PVR:["Puerto Vallarta","Mexico","🇲🇽"],
    PWQ:["Pavlodar","Kazakhstan","🇰🇿"],
    PZB:["Pietermaritzburg","South Africa","🇿🇦"],
    PZU:["Port Sudan","Sudan","🇸🇩"],
    QOW:["Owerri","Nigeria","🇳🇬"],
    QSF:["Setif","Algeria","🇩🇿"],
    QSR:["Salerno","Italy","🇮🇹"],
    RAI:["Praia","Cape Verde","🇨🇻"],
    RAR:["Rarotonga","Cook Islands","🇨🇰"],
    RBA:["Rabat","Morocco","🇲🇦"],
    RDU:["Raleigh","USA","🇺🇸"],
    REC:["Recife","Brazil","🇧🇷"],
    REK:["Reykjavik","Iceland","🇮🇸"],
    REN:["Orenburg","Russia","🇷🇺"],
    RGK:["Gorno-Altaysk","Russia","🇷🇺"],
    RGN:["Yangon","Myanmar","🇲🇲"],
    RHE:["Reims","France","🇫🇷"],
    RIO:["Rio de Janeiro","Brazil","🇧🇷"],
    RJK:["Rijeka","Croatia","🇭🇷"],
    RKT:["Ras Al Khaimah","UAE","🇦🇪"],
    RMA:["Roma","Australia","🇦🇺"],
    RMF:["Marsa Alam","Egypt","🇪🇬"],
    RMI:["Rimini","Italy","🇮🇹"],
    RMU:["Murcia","Spain","🇪🇸"],
    RNS:["Rennes","France","🇫🇷"],
    ROC:["Rochester","USA","🇺🇸"],
    RRG:["Rodrigues Island","Mauritius","🇲🇺"],
    RTM:["Rotterdam","Netherlands","🇳🇱"],
    RTW:["Saratov","Russia","🇷🇺"],
    RUH:["Riyadh","Saudi Arabia","🇸🇦"],
    RVN:["Rovaniemi","Finland","🇫🇮"],
    RZE:["Rzeszow","Poland","🇵🇱"],
    RZH:["Preobrazheniye","Russia","🇷🇺"],
    SAC:["Sacramento","USA","🇺🇸"],
    SAI:["Siem Reap","Cambodia","🇰🇭"],
    SAN:["San Diego","USA","🇺🇸"],
    SAO:["Sao Paulo","Brazil","🇧🇷"],
    SAV:["Savannah","USA","🇺🇸"],
    SBZ:["Sibiu","Romania","🇷🇴"],
    SCL:["Santiago","Chile","🇨🇱"],
    SCO:["Aktau","Kazakhstan","🇰🇿"],
    SCQ:["Santiago De Compostela","Spain","🇪🇸"],
    SCR:["SÃ¤len","Sweden","🇸🇪"],
    SCW:["Syktyvkar","Russia","🇷🇺"],
    SCY:["San Cristobal","Ecuador","🇪🇨"],
    SDQ:["Santo Domingo","Dominican Republic","🇩🇴"],
    SDR:["Santander","Spain","🇪🇸"],
    SDZ:["Shetland Islands","United Kingdom","🇬🇧"],
    SEA:["Seattle","USA","🇺🇸"],
    SEL:["Seoul","South Korea","🇰🇷"],
    SEZ:["Mahe","Seychelles","🇸🇨"],
    SFA:["Sfax","Tunisia","🇹🇳"],
    SFO:["San Francisco","USA","🇺🇸"],
    SGC:["Surgut","Russia","🇷🇺"],
    SGN:["Ho Chi Minh City","Vietnam","🇻🇳"],
    SHA:["Shanghai","China","🇨🇳"],
    SHE:["Shenyang","China","🇨🇳"],
    SHJ:["Sharjah","UAE","🇦🇪"],
    SIA:["Xian","China","🇨🇳"],
    SID:["Sal","Cape Verde","🇨🇻"],
    SIN:["Singapore","Singapore","🇸🇬"],
    SJD:["San Jose Del Cabo","Mexico","🇲🇽"],
    SJJ:["Sarajevo","Bosnia and Herzegovina","🇧🇦"],
    SJU:["San Juan","Puerto Rico","🇵🇷"],
    SKB:["Basseterre","Saint Kitts and Nevis","🇰🇳"],
    SKG:["Thessaloniki","Greece","🇬🇷"],
    SKP:["Skopje","Macedonia","🇲🇰"],
    SKT:["Sialkot","Pakistan","🇵🇰"],
    SKX:["Saransk","Russia","🇷🇺"],
    SLC:["Salt Lake City","USA","🇺🇸"],
    SLU:["Castries","Saint Lucia","🇱🇨"],
    SLY:["Salekhard","Russia","🇷🇺"],
    SOF:["Sofia","Bulgaria","🇧🇬"],
    SOQ:["Sorong","Indonesia","🇮🇩"],
    SPC:["Santa Cruz De La Palma","Spain","🇪🇸"],
    SPK:["Sapporo","Japan","🇯🇵"],
    SRZ:["Santa Cruz","Bolivia","🇧🇴"],
    SSA:["Salvador","Brazil","🇧🇷"],
    STI:["Santiago","Dominican Republic","🇩🇴"],
    STO:["Stockholm","Sweden","🇸🇪"],
    STR:["Stuttgart","Germany","🇩🇪"],
    STW:["Stavropol","Russia","🇷🇺"],
    SUB:["Surabaya","Indonesia","🇮🇩"],
    SUF:["Lamezia Terme","Italy","🇮🇹"],
    SUI:["Sukhumi","Abkhazia","🇦🇧"],
    SVG:["Stavanger","Norway","🇳🇴"],
    SVJ:["Svolvaer","Norway","🇳🇴"],
    SVX:["Yekaterinburg","Russia","🇷🇺"],
    SWA:["Shantou","China","🇨🇳"],
    SXB:["Strasbourg","France","🇫🇷"],
    SYX:["Sanya","China","🇨🇳"],
    SYY:["Stornoway","United Kingdom","🇬🇧"],
    SZF:["Samsun","Turkiye","🇹🇷"],
    SZG:["Salzburg","Austria","🇦🇹"],
    SZX:["Shenzhen","China","🇨🇳"],
    SZY:["Szymany","Poland","🇵🇱"],
    SZZ:["Szczecin","Poland","🇵🇱"],
    TAE:["Daegu","South Korea","🇰🇷"],
    TAO:["Qingdao","China","🇨🇳"],
    TAT:["Poprad","Slovakia","🇸🇰"],
    TAY:["Tartu","Estonia","🇪🇪"],
    TBW:["Tambov","Russia","🇷🇺"],
    TGD:["Podgorica","Montenegro","🇲🇪"],
    THD:["Thanh Hoa","Vietnam","🇻🇳"],
    THE:["Teresina","Brazil","🇧🇷"],
    TIA:["Tirana","Albania","🇦🇱"],
    TIF:["Taif","Saudi Arabia","🇸🇦"],
    TIV:["Tivat","Montenegro","🇲🇪"],
    TJM:["Tyumen","Russia","🇷🇺"],
    TJU:["Kulyab","Tajikistan","🇹🇯"],
    TKU:["Turku","Finland","🇫🇮"],
    TLS:["Toulouse","France","🇫🇷"],
    TMJ:["Termez","Uzbekistan","🇺🇿"],
    TMP:["Tampere","Finland","🇫🇮"],
    TNG:["Tangier","Morocco","🇲🇦"],
    TNR:["Antananarivo","Madagascar","🇲🇬"],
    TOF:["Tomsk","Russia","🇷🇺"],
    TPA:["Tampa","USA","🇺🇸"],
    TPE:["Taipei","Taiwan","🇹🇼"],
    TPS:["Trapani","Italy","🇮🇹"],
    TQO:["Tulum","Mexico","🇲🇽"],
    TRD:["Trondheim","Norway","🇳🇴"],
    TRN:["Turin","Italy","🇮🇹"],
    TRS:["Trieste","Italy","🇮🇹"],
    TRV:["Thiruvananthapuram","India","🇮🇳"],
    TSN:["Tianjin","China","🇨🇳"],
    TSR:["Timisoara","Romania","🇷🇴"],
    TTU:["Tetuan","Morocco","🇲🇦"],
    TUF:["Tours","France","🇫🇷"],
    TUL:["Tulsa","USA","🇺🇸"],
    TUN:["Tunis","Tunisia","🇹🇳"],
    TUS:["Tucson","USA","🇺🇸"],
    TVC:["Traverse City","USA","🇺🇸"],
    TYO:["Tokyo","Japan","🇯🇵"],
    TYS:["Knoxville","USA","🇺🇸"],
    TZL:["Tuzla","Bosnia and Herzegovina","🇧🇦"],
    TZX:["Trabzon","Turkiye","🇹🇷"],
    UBN:["Ulaanbaatar","Mongolia","🇲🇳"],
    UFA:["Ufa","Russia","🇷🇺"],
    UIH:["Qui Nhon","Vietnam","🇻🇳"],
    UIO:["Quito","Ecuador","🇪🇨"],
    UKK:["Oskemen","Kazakhstan","🇰🇿"],
    ULY:["Ulyanovsk","Russia","🇷🇺"],
    UME:["Umea","Sweden","🇸🇪"],
    UPG:["Makassar","Indonesia","🇮🇩"],
    URA:["Oral","Kazakhstan","🇰🇿"],
    URC:["Urumqi","China","🇨🇳"],
    URT:["Surat Thani","Thailand","🇹🇭"],
    USA:["Concord","USA","🇺🇸"],
    USM:["Koh Samui","Thailand","🇹🇭"],
    UTP:["Pattaya","Thailand","🇹🇭"],
    UUD:["Ulan-Ude","Russia","🇷🇺"],
    UUS:["Yuzhno-Sakhalinsk","Russia","🇷🇺"],
    VAA:["Vaasa","Finland","🇫🇮"],
    VAR:["Varna","Bulgaria","🇧🇬"],
    VBY:["Visby","Sweden","🇸🇪"],
    VCS:["Con Dao","Vietnam","🇻🇳"],
    VLN:["Valencia","Venezuela","🇻🇪"],
    VNX:["Vilanculos","Mozambique","🇲🇿"],
    VOG:["Volgograd","Russia","🇷🇺"],
    VRN:["Verona","Italy","🇮🇹"],
    VVO:["Vladivostok","Russia","🇷🇺"],
    WDH:["Windhoek","Namibia","🇳🇦"],
    WLG:["Wellington","New Zealand","🇳🇿"],
    WRE:["Whangarei","New Zealand","🇳🇿"],
    WRY:["Westray","United Kingdom","🇬🇧"],
    WUH:["Wuhan","China","🇨🇳"],
    XMN:["Xiamen","China","🇨🇳"],
    XRY:["Jerez de la Frontera","Spain","🇪🇸"],
    YEA:["Edmonton","Canada","🇨🇦"],
    YHZ:["Halifax","Canada","🇨🇦"],
    YKS:["Yakutsk","Russia","🇷🇺"],
    YLW:["Kelowna","Canada","🇨🇦"],
    YMQ:["Montreal","Canada","🇨🇦"],
    YOW:["Ottawa","Canada","🇨🇦"],
    YQY:["Sydney","Canada","🇨🇦"],
    YVR:["Vancouver","Canada","🇨🇦"],
    YWG:["Winnipeg","Canada","🇨🇦"],
    YXU:["London","Canada","🇨🇦"],
    YYG:["Charlottetown","Canada","🇨🇦"],
    YYT:["St. John's","Canada","🇨🇦"],
    YZS:["Coral Harbour","Canada","🇨🇦"],
    ZAD:["Zadar","Croatia","🇭🇷"],
    ZAG:["Zagreb","Croatia","🇭🇷"],
    ZAZ:["Zaragoza","Spain","🇪🇸"],
    ZNZ:["Zanzibar","Tanzania","🇹🇿"],
    ZQN:["Queenstown","New Zealand","🇳🇿"],
    ZYL:["Sylhet","Bangladesh","🇧🇩"],
    DKR:["Dakar","Senegal","🇸🇳"],
    HPH:["Haiphong","Vietnam","🇻🇳"],
    KZO:["Kzyl-Orda","Kazakhstan","🇰🇿"],
    MHT:["Manchester","USA","🇺🇸"],
    MSO:["Missoula","USA","🇺🇸"],
    STL:["St Louis","USA","🇺🇸"],
    ASM:["Asmara","Eritrea","🇪🇷"],
    BLA:["Barcelona","Venezuela","🇻🇪"],
    GPS:["Galapagos Islands","Ecuador","🇪🇨"],
    LPB:["La Paz","Bolivia","🇧🇴"],
    MEM:["Memphis","USA","🇺🇸"],
    PWM:["Portland","USA","🇺🇸"],
    RZV:["Rize","Turkiye","🇹🇷"],
    SMA:["Santa Maria","Portugal","🇵🇹"],
    VFA:["Victoria Falls","Zimbabwe","🇿🇼"]
};
