/* Destination names and flags, in one place.
 *
 * The search page, the homepage teaser and the twelve join pages all
 * need to turn an airport code into a city name and a flag. When only
 * the search knew them, two codes with no entry (BSZ, DSE) silently
 * vanished from the results, so this now lives on its own and the daily
 * job shouts if a new code turns up without a name.
 *
 * search.js keeps its own copy so it never depends on load order.
 */
window.CH_PLACES = {
    BCN:["Barcelona","Spain","🇪🇸"],AYT:["Antalya","Türkiye","🇹🇷"],
    IST:["Istanbul","Türkiye","🇹🇷"],MOW:["Moscow","Russia","🇷🇺"],
    LED:["St Petersburg","Russia","🇷🇺"],EDI:["Edinburgh","Scotland","🏴"],
    PAR:["Paris","France","🇫🇷"],AGP:["Málaga","Spain","🇪🇸"],
    ALC:["Alicante","Spain","🇪🇸"],OSS:["Osh","Kyrgyzstan","🇰🇬"],
    FAO:["Faro","Portugal","🇵🇹"],TAS:["Tashkent","Uzbekistan","🇺🇿"],
    BFS:["Belfast","N. Ireland","🇬🇧"],KRK:["Kraków","Poland","🇵🇱"],
    AMS:["Amsterdam","Netherlands","🇳🇱"],PMI:["Palma","Spain","🇪🇸"],
    LIS:["Lisbon","Portugal","🇵🇹"],BAK:["Baku","Azerbaijan","🇦🇿"],
    ACE:["Lanzarote","Spain","🇪🇸"],MAD:["Madrid","Spain","🇪🇸"],
    BKK:["Bangkok","Thailand","🇹🇭"],LON:["London","England","🏴"],
    YTO:["Toronto","Canada","🇨🇦"],PRG:["Prague","Czechia","🇨🇿"],
    ALA:["Almaty","Kazakhstan","🇰🇿"],SKD:["Samarkand","Uzbekistan","🇺🇿"],
    DUB:["Dublin","Ireland","🇮🇪"],WAW:["Warsaw","Poland","🇵🇱"],
    BER:["Berlin","Germany","🇩🇪"],LPA:["Gran Canaria","Spain","🇪🇸"],
    BEG:["Belgrade","Serbia","🇷🇸"],NYC:["New York","USA","🇺🇸"],
    DUS:["Düsseldorf","Germany","🇩🇪"],RMO:["Chișinău","Moldova","🇲🇩"],
    GRO:["Girona","Spain","🇪🇸"],HAM:["Hamburg","Germany","🇩🇪"],
    TCI:["Tenerife","Spain","🇪🇸"],CIT:["Shymkent","Kazakhstan","🇰🇿"],
    DLM:["Dalaman","Türkiye","🇹🇷"],CPH:["Copenhagen","Denmark","🇩🇰"],
    HEL:["Helsinki","Finland","🇫🇮"],DXB:["Dubai","UAE","🇦🇪"],
    CGN:["Cologne","Germany","🇩🇪"],BIO:["Bilbao","Spain","🇪🇸"],
    DYU:["Dushanbe","Tajikistan","🇹🇯"],TBS:["Tbilisi","Georgia","🇬🇪"],
    BUD:["Budapest","Hungary","🇭🇺"],NQZ:["Astana","Kazakhstan","🇰🇿"],
    OSL:["Oslo","Norway","🇳🇴"],OPO:["Porto","Portugal","🇵🇹"],
    IZM:["Izmir","Türkiye","🇹🇷"],GLA:["Glasgow","Scotland","🏴"],
    ROM:["Rome","Italy","🇮🇹"],VIE:["Vienna","Austria","🇦🇹"],
    LOS:["Lagos","Nigeria","🇳🇬"],BRS:["Bristol","England","🏴"],
    LHE:["Lahore","Pakistan","🇵🇰"],JNB:["Johannesburg","South Africa","🇿🇦"],
    HKG:["Hong Kong","Hong Kong","🇭🇰"],VNO:["Vilnius","Lithuania","🇱🇹"],
    BRI:["Bari","Italy","🇮🇹"],KZN:["Kazan","Russia","🇷🇺"],
    AGA:["Agadir","Morocco","🇲🇦"],CWL:["Cardiff","Wales","🏴"],
    MLA:["Malta","Malta","🇲🇹"],MAN:["Manchester","England","🏴"],
    REU:["Reus","Spain","🇪🇸"],JMK:["Mykonos","Greece","🇬🇷"],
    HKT:["Phuket","Thailand","🇹🇭"],SYD:["Sydney","Australia","🇦🇺"],
    BHX:["Birmingham","England","🏴"],AER:["Sochi","Russia","🇷🇺"],
    KRR:["Krasnodar","Russia","🇷🇺"],ILY:["Islay","Scotland","🏴"],
    KOI:["Kirkwall","Scotland","🏴"],FRA:["Frankfurt","Germany","🇩🇪"],
    GBE:["Gaborone","Botswana","🇧🇼"],MCX:["Makhachkala","Russia","🇷🇺"],
    LPL:["Liverpool","England","🏴"],RAK:["Marrakesh","Morocco","🇲🇦"],
    OLB:["Olbia","Italy","🇮🇹"],FUE:["Fuerteventura","Spain","🇪🇸"],
    PFO:["Paphos","Cyprus","🇨🇾"],ORK:["Cork","Ireland","🇮🇪"],
    NCL:["Newcastle","England","🏴"],KUN:["Kaunas","Lithuania","🇱🇹"],
    DBV:["Dubrovnik","Croatia","🇭🇷"],CLT:["Charlotte","USA","🇺🇸"],
    MSQ:["Minsk","Belarus","🇧🇾"],CAG:["Cagliari","Italy","🇮🇹"],
    KTT:["Kittilä","Finland","🇫🇮"],PRN:["Pristina","Kosovo","🇽🇰"],
    FAE:["Faroe Islands","Faroes","🇫🇴"],ORL:["Orlando","USA","🇺🇸"],
    MIR:["Monastir","Tunisia","🇹🇳"],HAK:["Haikou","China","🇨🇳"],
    EBL:["Erbil","Iraq","🇮🇶"],CAI:["Cairo","Egypt","🇪🇬"],
    FNA:["Freetown","Sierra Leone","🇸🇱"],JED:["Jeddah","Saudi Arabia","🇸🇦"],
    GDN:["Gdańsk","Poland","🇵🇱"],ACC:["Accra","Ghana","🇬🇭"],
    ATQ:["Amritsar","India","🇮🇳"],BUH:["Bucharest","Romania","🇷🇴"],
    BOD:["Bordeaux","France","🇫🇷"],CLJ:["Cluj-Napoca","Romania","🇷🇴"],
    BOS:["Boston","USA","🇺🇸"],BOJ:["Burgas","Bulgaria","🇧🇬"],
    GIB:["Gibraltar","Gibraltar","🇬🇮"],IBZ:["Ibiza","Spain","🇪🇸"],
    CHQ:["Chania","Greece","🇬🇷"],CFU:["Corfu","Greece","🇬🇷"],
    KTM:["Kathmandu","Nepal","🇳🇵"],SJO:["San José","Costa Rica","🇨🇷"],
    NCE:["Nice","France","🇫🇷"],KUT:["Kutaisi","Georgia","🇬🇪"],
    BUS:["Batumi","Georgia","🇬🇪"],ZTH:["Zakynthos","Greece","🇬🇷"],
    SSH:["Sharm el-Sheikh","Egypt","🇪🇬"],MIL:["Milan","Italy","🇮🇹"],
    ABV:["Abuja","Nigeria","🇳🇬"],ISB:["Islamabad","Pakistan","🇵🇰"],
    BRU:["Brussels","Belgium","🇧🇪"],BJV:["Bodrum","Türkiye","🇹🇷"],
    BSZ:["Bartica","Guyana","🇬🇾"],DSE:["Dessie","Ethiopia","🇪🇹"],
    ABZ:["Aberdeen","United Kingdom","🇬🇧"],
    AJA:["Ajaccio","France","🇫🇷"],
    AUA:["Oranjestad","Aruba","🇦🇼"],
    BLR:["Bengaluru","India","🇮🇳"],
    BNX:["Banja Luka","Bosnia and Herzegovina","🇧🇦"],
    BOH:["Bournemouth","United Kingdom","🇬🇧"],
    BUF:["Buffalo","USA","🇺🇸"],
    CFN:["Carrickfinn","Ireland","🇮🇪"],
    CMF:["Chambery","France","🇫🇷"],
    COK:["Kochi","India","🇮🇳"],
    CUN:["Cancun","Mexico","🇲🇽"],
    DAC:["Dhaka","Bangladesh","🇧🇩"],
    EAP:["Basel","Switzerland","🇨🇭"],
    EVN:["Yerevan","Armenia","🇦🇲"],
    EXT:["Exeter","United Kingdom","🇬🇧"],
    GRV:["Groznyy","Russia","🇷🇺"],
    GVA:["Geneva","Switzerland","🇨🇭"],
    HER:["Heraklion","Greece","🇬🇷"],
    INV:["Inverness","United Kingdom","🇬🇧"],
    JLR:["Jabalpur","India","🇮🇳"],
    KCH:["Kuching","Malaysia","🇲🇾"],
    KUU:["Bhuntar Kullu","India","🇮🇳"],
    LCA:["Larnaca","Cyprus","🇨🇾"],
    LUX:["Luxembourg","Luxembourg","🇱🇺"],
    MAH:["Menorca","Spain","🇪🇸"],
    MUX:["Multan","Pakistan","🇵🇰"],
    NBC:["Naberezhnye Chelny","Russia","🇷🇺"],
    NQY:["Newquay","United Kingdom","🇬🇧"],
    NWI:["Norwich","United Kingdom","🇬🇧"],
    OST:["Bruges","Belgium","🇧🇪"],
    OVB:["Novosibirsk","Russia","🇷🇺"],
    RHO:["Rhodes","Greece","🇬🇷"],
    RIX:["Riga","Latvia","🇱🇻"],
    SCV:["Suceava","Romania","🇷🇴"],
    SNN:["Shannon","Ireland","🇮🇪"],
    SOU:["Southampton","United Kingdom","🇬🇧"],
    SPU:["Split","Croatia","🇭🇷"],
    SVQ:["Sevilla","Spain","🇪🇸"],
    TLL:["Tallinn","Estonia","🇪🇪"],
    TOS:["Tromso","Norway","🇳🇴"],
    UGC:["Urgench","Uzbekistan","🇺🇿"],
    VCE:["Venice","Italy","🇮🇹"],
    VLC:["Valencia","Spain","🇪🇸"],
    WAS:["Washington","USA","🇺🇸"],
    WRO:["Wroclaw","Poland","🇵🇱"],
    YYC:["Calgary","Canada","🇨🇦"],
    ZRH:["Zurich","Switzerland","🇨🇭"]
};
